import { Currency, Bank } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'AED', name: 'UAE Dirham', numericCode: '784' },
  { code: 'AFN', name: 'Afghan Afghani', numericCode: '971' },
  { code: 'ALL', name: 'Albanian Lek', numericCode: '008' },
  { code: 'AMD', name: 'Armenian Dram', numericCode: '051' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', numericCode: '532' },
  { code: 'AOA', name: 'Angolan Kwanza', numericCode: '973' },
  { code: 'ARS', name: 'Argentine Peso', numericCode: '032' },
  { code: 'AUD', name: 'Australian Dollar', numericCode: '036' },
  { code: 'AWG', name: 'Aruban Florin', numericCode: '533' },
  { code: 'AZN', name: 'Azerbaijani Manat', numericCode: '944' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', numericCode: '977' },
  { code: 'BBD', name: 'Barbadian Dollar', numericCode: '052' },
  { code: 'BDT', name: 'Bangladeshi Taka', numericCode: '050' },
  { code: 'BGN', name: 'Bulgarian Lev', numericCode: '975' },
  { code: 'BHD', name: 'Bahraini Dinar', numericCode: '048' },
  { code: 'BIF', name: 'Burundian Franc', numericCode: '108' },
  { code: 'BMD', name: 'Bermudian Dollar', numericCode: '060' },
  { code: 'BND', name: 'Brunei Dollar', numericCode: '096' },
  { code: 'BOB', name: 'Bolivian Boliviano', numericCode: '068' },
  { code: 'BRL', name: 'Brazilian Real', numericCode: '986' },
  { code: 'BSD', name: 'Bahamian Dollar', numericCode: '044' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', numericCode: '064' },
  { code: 'BWP', name: 'Botswanan Pula', numericCode: '072' },
  { code: 'BYN', name: 'Belarusian Ruble', numericCode: '933' },
  { code: 'BZD', name: 'Belize Dollar', numericCode: '084' },
  { code: 'CAD', name: 'Canadian Dollar', numericCode: '124' },
  { code: 'CDF', name: 'Congolese Franc', numericCode: '976' },
  { code: 'CHF', name: 'Swiss Franc', numericCode: '756' },
  { code: 'CLP', name: 'Chilean Peso', numericCode: '152' },
  { code: 'CNY', name: 'Chinese Yuan', numericCode: '156' },
  { code: 'COP', name: 'Colombian Peso', numericCode: '170' },
  { code: 'CRC', name: 'Costa Rican Colón', numericCode: '188' },
  { code: 'CUC', name: 'Cuban Convertible Peso', numericCode: '931' },
  { code: 'CUP', name: 'Cuban Peso', numericCode: '192' },
  { code: 'CVE', name: 'Cape Verdean Escudo', numericCode: '132' },
  { code: 'CZK', name: 'Czech Republic Koruna', numericCode: '203' },
  { code: 'DJF', name: 'Djiboutian Franc', numericCode: '262' },
  { code: 'DKK', name: 'Danish Krone', numericCode: '208' },
  { code: 'DOP', name: 'Dominican Peso', numericCode: '214' },
  { code: 'DZD', name: 'Algerian Dinar', numericCode: '012' },
  { code: 'EGP', name: 'Egyptian Pound', numericCode: '818' },
  { code: 'ERN', name: 'Eritrean Nakfa', numericCode: '232' },
  { code: 'ETB', name: 'Ethiopian Birr', numericCode: '230' },
  { code: 'EUR', name: 'Euro', numericCode: '978' },
  { code: 'FJD', name: 'Fijian Dollar', numericCode: '242' },
  { code: 'FKP', name: 'Falkland Islands Pound', numericCode: '238' },
  { code: 'GBP', name: 'British Pound', numericCode: '826' },
  { code: 'GEL', name: 'Georgian Lari', numericCode: '981' },
  { code: 'GGP', name: 'Guernsey Pound', numericCode: '831' },
  { code: 'GHS', name: 'Ghanaian Cedi', numericCode: '936' },
  { code: 'GIP', name: 'Gibraltar Pound', numericCode: '292' },
  { code: 'GMD', name: 'Gambian Dalasi', numericCode: '270' },
  { code: 'GNF', name: 'Guinean Franc', numericCode: '324' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', numericCode: '320' },
  { code: 'GYD', name: 'Guyanaese Dollar', numericCode: '328' },
  { code: 'HKD', name: 'Hong Kong Dollar', numericCode: '344' },
  { code: 'HNL', name: 'Honduran Lempira', numericCode: '340' },
  { code: 'HRK', name: 'Croatian Kuna', numericCode: '191' },
  { code: 'HTG', name: 'Haitian Gourde', numericCode: '332' },
  { code: 'HUF', name: 'Hungarian Forint', numericCode: '348' },
  { code: 'IDR', name: 'Indonesian Rupiah', numericCode: '360' },
  { code: 'ILS', name: 'Israeli New Sheqel', numericCode: '376' },
  { code: 'IMP', name: 'Manx pound', numericCode: '833' },
  { code: 'INR', name: 'Indian Rupee', numericCode: '356' },
  { code: 'IQD', name: 'Iraqi Dinar', numericCode: '368' },
  { code: 'IRR', name: 'Iranian Rial', numericCode: '364' },
  { code: 'ISK', name: 'Icelandic Króna', numericCode: '352' },
  { code: 'JEP', name: 'Jersey Pound', numericCode: '832' },
  { code: 'JMD', name: 'Jamaican Dollar', numericCode: '388' },
  { code: 'JOD', name: 'Jordanian Dinar', numericCode: '400' },
  { code: 'JPY', name: 'Japanese Yen', numericCode: '392' },
  { code: 'KES', name: 'Kenyan Shilling', numericCode: '404' },
  { code: 'KGS', name: 'Kyrgystani Som', numericCode: '417' },
  { code: 'KHR', name: 'Cambodian Riel', numericCode: '116' },
  { code: 'KMF', name: 'Comorian Franc', numericCode: '174' },
  { code: 'KPW', name: 'North Korean Won', numericCode: '408' },
  { code: 'KRW', name: 'South Korean Won', numericCode: '410' },
  { code: 'KWD', name: 'Kuwaiti Dinar', numericCode: '414' },
  { code: 'KYD', name: 'Cayman Islands Dollar', numericCode: '136' },
  { code: 'KZT', name: 'Kazakhstani Tenge', numericCode: '398' },
  { code: 'LAK', name: 'Laotian Kip', numericCode: '418' },
  { code: 'LBP', name: 'Lebanese Pound', numericCode: '422' },
  { code: 'LKR', name: 'Sri Lankan Rupee', numericCode: '144' },
  { code: 'LRD', name: 'Liberian Dollar', numericCode: '430' },
  { code: 'LSL', name: 'Lesotho Loti', numericCode: '426' },
  { code: 'LYD', name: 'Libyan Dinar', numericCode: '434' },
  { code: 'MAD', name: 'Moroccan Dirham', numericCode: '504' },
  { code: 'MDL', name: 'Moldovan Leu', numericCode: '498' },
  { code: 'MGA', name: 'Malagasy Ariary', numericCode: '969' },
  { code: 'MKD', name: 'Macedonian Denar', numericCode: '807' },
  { code: 'MMK', name: 'Myanma Kyat', numericCode: '104' },
  { code: 'MNT', name: 'Mongolian Tugrik', numericCode: '496' },
  { code: 'MOP', name: 'Macanese Pataca', numericCode: '446' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', numericCode: '929' },
  { code: 'MUR', name: 'Mauritian Rupee', numericCode: '480' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', numericCode: '462' },
  { code: 'MWK', name: 'Malawian Kwacha', numericCode: '454' },
  { code: 'MXN', name: 'Mexican Peso', numericCode: '484' },
  { code: 'MYR', name: 'Malaysian Ringgit', numericCode: '458' },
  { code: 'MZN', name: 'Mozambican Metical', numericCode: '943' },
  { code: 'NAD', name: 'Namibian Dollar', numericCode: '516' },
  { code: 'NGN', name: 'Nigerian Naira', numericCode: '566' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', numericCode: '558' },
  { code: 'NOK', name: 'Norwegian Krone', numericCode: '578' },
  { code: 'NPR', name: 'Nepalese Rupee', numericCode: '524' },
  { code: 'NZD', name: 'New Zealand Dollar', numericCode: '554' },
  { code: 'OMR', name: 'Omani Rial', numericCode: '512' },
  { code: 'PAB', name: 'Panamanian Balboa', numericCode: '590' },
  { code: 'PEN', name: 'Peruvian Nuevo Sol', numericCode: '604' },
  { code: 'PGK', name: 'Papua New Guinean Kina', numericCode: '598' },
  { code: 'PHP', name: 'Philippine Peso', numericCode: '608' },
  { code: 'PKR', name: 'Pakistani Rupee', numericCode: '586' },
  { code: 'PLN', name: 'Polish Zloty', numericCode: '985' },
  { code: 'PYG', name: 'Paraguayan Guarani', numericCode: '600' },
  { code: 'QAR', name: 'Qatari Rial', numericCode: '634' },
  { code: 'RON', name: 'Romanian Leu', numericCode: '946' },
  { code: 'RSD', name: 'Serbian Dinar', numericCode: '941' },
  { code: 'RUB', name: 'Russian Ruble', numericCode: '643' },
  { code: 'RWF', name: 'Rwandan Franc', numericCode: '646' },
  { code: 'SAR', name: 'Saudi Riyal', numericCode: '682' },
  { code: 'SBD', name: 'Solomon Islands Dollar', numericCode: '090' },
  { code: 'SCR', name: 'Seychellois Rupee', numericCode: '690' },
  { code: 'SDG', name: 'Sudanese Pound', numericCode: '938' },
  { code: 'SEK', name: 'Swedish Krona', numericCode: '752' },
  { code: 'SGD', name: 'Singapore Dollar', numericCode: '702' },
  { code: 'SHP', name: 'Saint Helena Pound', numericCode: '654' },
  { code: 'SLL', name: 'Sierra Leonean Leone', numericCode: '694' },
  { code: 'SOS', name: 'Somali Shilling', numericCode: '706' },
  { code: 'SRD', name: 'Surinamese Dollar', numericCode: '968' },
  { code: 'SSP', name: 'South Sudanese Pound', numericCode: '728' },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', numericCode: '930' },
  { code: 'SVC', name: 'Salvadoran Colón', numericCode: '222' },
  { code: 'SYP', name: 'Syrian Pound', numericCode: '760' },
  { code: 'SZL', name: 'Swazi Lilangeni', numericCode: '748' },
  { code: 'THB', name: 'Thai Baht', numericCode: '764' },
  { code: 'TJS', name: 'Tajikistani Somoni', numericCode: '972' },
  { code: 'TMT', name: 'Turkmenistani Manat', numericCode: '934' },
  { code: 'TND', name: 'Tunisian Dinar', numericCode: '788' },
  { code: 'TOP', name: 'Tongan Pa anga', numericCode: '776' },
  { code: 'TRY', name: 'Turkish Lira', numericCode: '949' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', numericCode: '780' },
  { code: 'TWD', name: 'New Taiwan Dollar', numericCode: '901' },
  { code: 'TZS', name: 'Tanzanian Shilling', numericCode: '834' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', numericCode: '980' },
  { code: 'UGX', name: 'Ugandan Shilling', numericCode: '800' },
  { code: 'USD', name: 'US Dollar', numericCode: '840' },
  { code: 'UYU', name: 'Uruguayan Peso', numericCode: '858' },
  { code: 'UZS', name: 'Uzbekistan Som', numericCode: '860' },
  { code: 'VES', name: 'Venezuelan Bolívar', numericCode: '928' },
  { code: 'VND', name: 'Vietnamese Dong', numericCode: '704' },
  { code: 'VUV', name: 'Vanuatu Vatu', numericCode: '548' },
  { code: 'WST', name: 'Samoan Tala', numericCode: '882' },
  { code: 'XAF', name: 'CFA Franc BEAC', numericCode: '950' },
  { code: 'XAG', name: 'Silver (troy ounce)', numericCode: '961' },
  { code: 'XAU', name: 'Gold (troy ounce)', numericCode: '959' },
  { code: 'XCD', name: 'East Caribbean Dollar', numericCode: '951' },
  { code: 'XDR', name: 'Special Drawing Rights', numericCode: '960' },
  { code: 'XOF', name: 'CFA Franc BCEAO', numericCode: '952' },
  { code: 'XPD', name: 'Palladium Ounce', numericCode: '964' },
  { code: 'XPF', name: 'CFP Franc', numericCode: '953' },
  { code: 'XPT', name: 'Platinum Ounce', numericCode: '962' },
  { code: 'YER', name: 'Yemeni Rial', numericCode: '886' },
  { code: 'ZAR', name: 'South African Rand', numericCode: '710' },
  { code: 'ZMW', name: 'Zambian Kwacha', numericCode: '967' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', numericCode: '932' }
];

export const BANKS: Bank[] = [
  { name: 'Chase', markupRate: 0.02 },
  { name: 'Bank of America', markupRate: 0.03 },
  { name: 'Wells Fargo', markupRate: 0.025 },
  { name: 'Citibank', markupRate: 0.027 },
]; 